project_id = "ojxzssooylmydystjvdo"

[functions.sync-ebay-orders]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.whatsapp-config]
verify_jwt = false

[functions.ebay-orders]
verify_jwt = false

[functions.orders-dashboard]
verify_jwt = false

[functions.admin-adjust-credits]
verify_jwt = false